# action.yml
name: 'Google java format analyzer'
description: 'Analyze formatting of Java files and prints a diff on incorrect formatted files'
inputs:
  path:
    description: 'path to repo'
    required: true
    default: "./"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}